image: docker:latest

services:
  - docker:dind

variables:
  LATEST_VER_HML: caleberios/gaia-ciclone:homolog
  LATEST_VER_PROD: caleberios/gaia-ciclone:latest

stages:
  - build
  - quality
  - pushImage
  - deploy

installDependencies:
  stage: build
  image: node:alpine
  script:
    - npm install

buildLocal:
  stage: build
  script:
    - docker build .

testCheck:
  stage: quality
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose run gaiaciclone npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

staticAnalysis:
  stage: quality
  image: node:alpine
  script:
    - npm install
    - npm run lint

pushHomolog:
  stage: pushImage
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_HML .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_HML && docker image rm $LATEST_VER_HML

pushProd:
  stage: pushImage
  only:
    - master
  script:
    - docker build -t $LATEST_VER_PROD .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_PROD && docker image rm $LATEST_VER_PROD

deployHomolog:
  stage: deploy
  image: google/cloud-sdk
  only:
    - dev
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete deployment.apps/gaia-ciclone-hml service/gaia-ciclone-hml
    - cat k8s/gaia_ciclone_hml.yaml | sed "s/{{CYCLONE_ID_HML}}/$CYCLONE_ID_HML/g" | sed "s/{{CYCLONE_SECRET_HML}}/$CYCLONE_SECRET_HML/g" | sed "s/{{DB}}/$DB/g" | sed "s/{{PASS_DB}}/$PASS_DB/g" | sed "s/{{USER_DB}}/$USER_DB/g" | kubectl apply -f -

deployProd:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete deployment.apps/gaia-ciclone service/gaia-ciclone
    - cat k8s/gaia_ciclone.yaml | sed "s/{{CYCLONE_ID}}/$CYCLONE_ID/g" | sed "s/{{CYCLONE_SECRET}}/$CYCLONE_SECRET/g" | sed "s/{{DB}}/$DB/g" | sed "s/{{PASS_DB}}/$PASS_DB/g" | sed "s/{{USER_DB}}/$USER_DB/g" | kubectl apply -f -
