version: '3'

services:
  gaiaciclone:
    build: .
    restart: always
    environment:
      - CYCLONE_ID=${CYCLONE_ID}
      - CYCLONE_SECRET=${CYCLONE_SECRET}
      - ENVIRONMENT=dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - mongociclone
  
  mongociclone:
    image: aashreys/mongo-auth:latest
    command: mongod --port 27018
    ports: 
      - 27018:27018
