apiVersion: v1
kind: Service
metadata:
  name: gaia-ciclone
spec:
  ports:
  - port: 443
    targetPort: 3001
  selector:
    app: gaia-ciclone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-ciclone
spec:
  selector:
    matchLabels:
      app: gaia-ciclone
  replicas: 1
  template:
    metadata:
      labels:
        app: gaia-ciclone
    spec:
      containers:
      - env:
        - name: API_KEY
          value: {{API_KEY}}
        image: caleberios/gaia-ciclone:latest
        imagePullPolicy: Always
        name: gaia-ciclone
        ports:
        - containerPort: 3001