apiVersion: v1
kind: Service
metadata:
  name: gaia-ciclone
spec:
  ports:
  - port: 443
    targetPort: 3001
  selector:
    app: gaia-ciclone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-ciclone
spec:
  selector:
    matchLabels:
      app: gaia-ciclone
  replicas: 1
  template:
    metadata:
      labels:
        app: gaia-ciclone
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: production
        - name: CYCLONE_ID
          value: {{CYCLONE_ID}}
        - name: CYCLONE_SECRET
          calue: {{CYCLONE_SECRET}}
        - name: DB
          value: {{DB}}
        - name: PASS_DB
          value: {{PASS_DB}}
        - name: USER_DB
          value: {{USER_DB}}
        image: caleberios/gaia-ciclone:latest
        imagePullPolicy: Always
        name: gaia-ciclone
        ports:
        - containerPort: 3001